-- Migration v6: superseded, intentionally a no-op.
--
-- This originally created a `clean_ips` table with columns
-- (ip PRIMARY KEY, latency_ms, healthy, last_checked, last_error). That
-- design was replaced before it ever shipped by the simpler admin-curated
-- list in schema.sql — CREATE TABLE IF NOT EXISTS clean_ips (id, ip, port,
-- note, country, created_at) — which is what src/db/queries.ts (listCleanIps
-- / addCleanIp / getBestCleanIp) actually reads and writes.
--
-- Because schema.sql runs first and creates the table with the *new*
-- columns, this file's old `CREATE TABLE IF NOT EXISTS` was a silent no-op
-- (table already existed) and its `CREATE INDEX ... (healthy, latency_ms)`
-- then failed on every single build/deploy with
-- "no such column: healthy" — harmless (ci-setup.js tolerates a failed
-- migration file and moves on) but noisy. Left empty rather than deleted so
-- historical deploy logs referencing "migration-v6.sql" still resolve to a
-- real file.
